name: rwid
description: "RWID Clone Medium"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.0.0
  google_sign_in: ^6.1.6
  another_flushbar: ^1.12.30
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  freezed_annotation: ^2.2.0
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  flutter_native_splash: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  hive_generator: ^2.0.1
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/icon_rwid.jpg"
  min_sdk_android: 21 # android

flutter_native_splash:
  image: assets/image/icon_rwid.jpg
  color: "#ffffff"
  android_12:
    image: assets/image/icon_rwid.jpg
    color: "#a7bbc7"

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
